version: '3.8'

services:
  api:
    build: 
      context: .
      args:
        ENVIRONMENT: dev
    environment:
      - PORT=8000
    container_name: api
    volumes:
      - ./:/src/
    ports:
      - 8000:8000
    restart: on-failure
