# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-09-10T14:58:16+00:00

from __future__ import annotations

from pydantic import BaseModel, confloat


class PredictModel(BaseModel):
    medinc: confloat(ge=0.0, le=50.0)
    averooms: confloat(ge=0.0, le=150.0)
